name: Christmas Email

on:
  schedule:
    - cron: '0 0 25 12 *'   
  workflow_dispatch:

jobs:
  run-christmas-email:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Print current time
      run: date -u

    - name: Install dependencies
      run: npm install

    - name: Run Christmas email job
      run: node send-christmas-email.js
